### ISSUE TITLE
Can not interact with contract

### ISSUE THREAD

**Issue by akhekade** [pranshurastogi/devpost_xinfin_hackathon#1]
Looking interesting. I checked the contract address, but it doesnt seem to be a contract but a normal XDC address. Can you double check please?

https://explorer.xinfin.network/addr/xdc6a6b80c5ee9fa2089d5c97de5e1a74667f68cd37

Also, is there a way to have UI for this for me or community to personally interact and use it?

**Comment by pranshurastogi** [comment]
@akhekade I have got this while deploying it through xinfin remix IDE. Although I have tested this with Truffle ethereum [ropsten network]. I agree there are some issues because it's not accepting the xinfin address in the contract as it shows that invalid. I just started with this so I am figuring out to make it compatible with XinFin. Although it works perfectly fine with Ethereum.
If you check I have redeployed and kind of get the same address https://explorer.xinfin.network/addr/xdca6fba219be011b5c00e387bbde7e802823617451


Regarding the UI thing, I am working on most probably it gets completed by year-end. Thanks for reviewing it, do let me know if you need any other assistance.


![image](https://user-images.githubusercontent.com/12568291/102728608-c9fb4900-4352-11eb-8bd6-a7b92a5bc1ca.png)

**Comment by akhekade** [comment]
Asked to check our Devs what the issue is. Let me know if you need anything to get this out to market.
